### ISSUE TITLE
Positive X bug.

### ISSUE THREAD

**Issue by TruKave** [MakerBox-NZ/pygame_trukavev2#3]
While going to the right, the player goes double the speed and won't die until I stop moving right.
Another thing that might be useful is that if I go far enough, theres a delay between me letting go and him dying.

EDIT: Done some more testing, and it turns out that instead of there being a delay between letting go of "D" and him dying, its if his x gets low enough (or enters a certain area).
EDIT2: While moving right scrolling is stopped until the player stops... this is getting confusing.

**Comment by cyanidecupcake** [comment]
I can't replicate this error, though I suspect it might have something to do with Issue #4.   

If fixing your indentation doesn't resolve this issue, please show me or @notklaatu  what you are experiencing in class tonight.

**Comment by TruKave** [comment]
It seems like now it happens with moving left too.
