### ISSUE TITLE
Will only scroll while not moving

### ISSUE THREAD

**Issue by TruKave** [MakerBox-NZ/pygame_trukavev2#5]
Scrolling doesn't work while the player is moving, instead it just updates when the player stops.

**Comment by cyanidecupcake** [comment]
Did you write the code for scrolling yet?  I don't see it in MAIN LOOP.

**Comment by cyanidecupcake** [comment]
Check your indentation for scroll forward and scroll backward.  It sounds like you may have accidentally put the code inside your arrow keys.

**Comment by TruKave** [comment]
@cyanidecupcake For some reason I thought I was supposed to, I don't know why.
